export const vacanciesListMock = [
  {
    id: 1,
    vacancyRole: 'desenvolvedor web front end',
    wage: 50000,
    location: 'são paulo',
    vacancyType: 'remoto',
    vacancyDescription: 'typescript',
    level: 'pleno',
    company: [],
    advertiser: [],
    technologies: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    deleteAt: null,
  },
  {
    id: 1,
    vacancyRole: 'desenvolvedor web front end',
    wage: 50000,
    location: 'são paulo',
    vacancyType: 'remoto',
    vacancyDescription: 'typescript',
    level: 'pleno',
    company: [],
    advertiser: [],
    technologies: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    deleteAt: null,
  },
  {
    id: 1,
    vacancyRole: 'desenvolvedor web front end',
    wage: 50000,
    location: 'são paulo',
    vacancyType: 'remoto',
    vacancyDescription: 'typescript',
    level: 'pleno',
    company: [],
    advertiser: [],
    technologies: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    deleteAt: null,
  },
];
